apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dgw-rb
  namespace: dgw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dgw-clusterrole
subjects:
- kind: ServiceAccount
  name: dgw
  namespace: dgw
