apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dxpgateway
  namespace: dgw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sdcard
  namespace: dgw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
