---
# - name: attempt to load in vars for workshop
#   ansible.builtin.include_vars:
#     file: "workshop_vars/{{ workshop_type }}.yml"

- name: include tasks to setup connections
  ansible.builtin.include_tasks:
    file: setup-connection.yml
  when:
    - teardown is not defined or
      not (teardown)
