---

- name: push out pod {{ pod.name }} yaml
  ansible.builtin.copy:
    content: "{{ pod.definition }}"
    dest: "{{ pod_dir }}/{{ pod.name }}.yml"
    owner: "{{ ansible_user }}"

- name: override state for 'absent'
  ansible.builtin.set_fact:
    pod_state: absent
    play_pod_state: absent
  when:
    - state is defined
    - state == 'absent'

- name: play yaml to create pod {{ pod.name }}
  containers.podman.podman_play:
    kube_file: "{{ pod_dir }}/{{ pod.name }}.yml"
    state: "{{ play_pod_state }}"

- name: Create systemd service unit file
  become: "{{ pod.privileged | default(false) }}"
  shell: |
    podman generate systemd --files --name  {{ pod.name }}
    for i in $(ls *.service)
    do 
      if [ "$(id -u)" = "0" ]; then
        mv -f $i /etc/systemd/system/
        restorecon  /etc/systemd/system/$i
        systemctl daemon-reload
        systemctl enable $i
      else
        mkdir -p {{ ansible_env.HOME }}/.config/systemd/user/
        mv -f $i {{ ansible_env.HOME }}/.config/systemd/user/
        systemctl daemon-reload --user
        systemctl enable --user $i
      fi
    done
  ignore_errors: true