---

- name: manage volumes
  containers.podman.podman_volume:
    name: "{{ volume.persistentVolumeClaim.claimName }}"
    state: "{{ state }}"
  loop: "{{ pod.spec.volumes }}"
  loop_control:
    loop_var: volume