---

# Login into Red Hat registry
- name: Login to redhat registry
  containers.podman.podman_login:
    username: '{{ redhat_username }}'
    password: '{{ redhat_password }}'
    registry: '{{ ee_registry_name }}'
  become_user: "{{ ansible_user }}"
  register: login_registry
  until: login_registry is not failed
  retries: 5
