---
## Execution environments

- name: Login to redhat registry
  containers.podman.podman_login:
    username: '{{ redhat_username }}'
    password: '{{ redhat_password }}'
    registry: '{{ ee_registry_name }}'
  become_user: "awx"

- name: Mod containers.conf to utilize max of 10 parallel threads
  become_user: "awx"
  lineinfile:
    path: /var/lib/awx/.config/containers/containers.conf
    line: 'image_parallel_copies=10'
    insertafter: EOF

- name: Pull supported images
  become_user: "awx"
  containers.podman.podman_image:
    name: "{{ item }}"
  loop: "{{ ee_images }}"
  register: podman_pull_supported
  until: podman_pull_supported is not failed
  retries: 5
  delay: 15

- name: create container registry credential
  awx.awx.credential:
    name: '{{ ee_registry_name }} credential'
    organization: Default
    credential_type: Container Registry
    controller_host: "https://{{ ansible_host }}:{{ nginx_https_port }}"
    controller_username: admin
    controller_password: "{{ admin_password }}"
    validate_certs: false
    inputs:
      username: "{{ redhat_username }}"
      password: "{{ redhat_password }}"
      host: "{{ ee_registry_name }}"

- name: update default EE to use credential
  awx.awx.execution_environment:
    name: "Default execution environment"
    image: "{{ ee_default_image }}"
    pull: missing
    credential: "registry.redhat.io credential"
    controller_username: admin
    controller_password: "{{ admin_password }}"
    controller_host: "https://{{ ansible_host }}:{{ nginx_https_port }}"
    validate_certs: false
  register: ee_check
  until: ee_check is not failed
  retries: 4
  delay: 5

### end of execution environments