---

- name: include tasks to manage dns records
  ansible.builtin.include_tasks:
    file: manage-dns-records.yml
  when:
    - teardown is not defined or
      (teardown is defined and not teardown|bool)

- name: include teardown tasks when needed
  ansible.builtin.include_tasks:
    file: teardown.yml
  when:
    - teardown|bool