---

_namespace:
  apiVersion: v1
  kind: Namespace
  metadata:
    name: ansible-automation-platform

_subscription:
  apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: ansible-automation-platform
    namespace: "{{ _namespace.metadata.name }}"
  spec:
    channel: 'stable-2.4'
    installPlanApproval: Automatic
    name: ansible-automation-platform-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
