apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: amq-broker
  annotations:
    skupper.io/address: amq-broker-hdls-svc-proxy
    skupper.io/port: '61616'
    skupper.io/proxy: tcp
  labels:
    app: amq-broker
spec:
  serviceName: amq-broker-hdls-svc
  replicas: 1
  selector:
    matchLabels:
      app: amq-broker
  template:
    metadata:
      labels:
        app: amq-broker
    spec:
      containers:
      - name: amq-broker
        image: {{ .Values.mqtt.image }}
        imagePullPolicy: IfNotPresent
        persistenceEnabled: true
        storage:
          size: 1Gi
        env:
        - name: AMQ_PROTOCOL
          value: all
        - name: AMQ_DATA_DIR
          value: /data
        - name: AMQ_USER
          value: admin
        - name: AMQ_PASSWORD
          value: admin
        ports:
         - containerPort: {{ .Values.mqtt.port }} # general
        volumeMounts:
          - name: amq-broker-datavol
            mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: amq-broker-datavol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi