id = "microshift-gitops-1.12"
name = "Red Hat OpenShift GitOps 1.12 for RHEL 9 x86_64 (RPMs)"
type = "yum-baseurl"
url = "https://cdn.redhat.com/content/dist/layered/rhel9/x86_64/gitops/1.12/os"
check_gpg = true
check_ssl = true
system = false
rhsm = true