id = "rhsi"
name = "Red Hat Service Interconnect 1.4"
type = "yum-baseurl"
url = "https://cdn.redhat.com/content/dist/layered/rhel9/x86_64/rhai/1/os"
check_gpg = true
check_ssl = true
system = false
rhsm = true