apiVersion: v1
kind: ConfigMap
metadata:
  name: ledblink-monitor-config
  namespace: cps
data:
  MODEL_ADDRESS: "http://model-get-cps.apps.192.168.3.100.nip.io"
  LED_ADDRESS: "http://ledblink-api-cps.apps.192.168.3.100.nip.io"
  SUB_TOPIC: "plc-state"
  PUB_TOPIC: "result"
  MQTT_BROKER_ADDRESS: "amq-broker-hdls-svc"
  MQTT_PORT: "61616"
  KAFKA_USE: "" # NULL -> MQTT mode, True -> Kafka mode
  KAFKA_BOOTSTRAP_SERVER: "my-cluster-kafka.demo.svc:9092"
  RED_PIN: "17"
  BLUE_PIN: "27"
  WHITE_PIN: "22"
  PER_CYCLES: "3"
  LED_API_TIMEOUT: "5.0"
  MODEL_GET_TIMEOUT: "3.0"