---

- name: push config files
  ansible.builtin.template:
    src: "templates/{{ template.src }}.j2"
    dest: "{{ template.dest }}"
  loop: "{{ wireless_ap_config_files }}"
  loop_control:
    loop_var: template
  notify:
    - restart_services
