---

- name: enable ipv4 forwarding
  ansible.builtin.copy:
    content: 'net.ipv4.ip_forward = 1'
    dest: /etc/sysctl.d/10-ip-forwarding.conf
  notify:
    - enable_ip_forwarding
    - restart_services

- name: apply iptables rule
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ wan_interface }}"
    jump: MASQUERADE
  notify:
    - restart_services
