---

- name: play kube file
  containers.podman.podman_play:
    kube_file: "/home/{{ ansible_user }}/{{ kube_spec.kube_file_content.metadata.name }}.yaml"
    state: started
  register: gitea_deployed

- name: give gitea time to start up
  ansible.builtin.wait_for:
    port: 3000
    delay: 60
  when:
    - gitea_deployed.changed
