---

- name: ensure podman is present
  ansible.builtin.dnf:
    name: podman
  become: true

- name: create local holding directories
  delegate_to: localhost
  block:
    - name: ensure parent {{ build_dir }} exists
      ansible.builtin.file:
        path: "{{ build_dir }}"
        state: directory
    - name: create parent {{ source_control_tmp_dir }} exists
      ansible.builtin.file:
        path: "{{ source_control_tmp_dir }}"
        state: directory

- name: enable lingering for {{ ansible_user }}
  ansible.builtin.shell:
    cmd: loginctl enable-linger {{ ansible_user }}
  args:
    creates: "/var/lib/systemd/linger/{{ ansible_user }}"
  become: true
