---

- name: print out image to compose
  ansible.builtin.debug:
    msg: "{{ image }}"

- name: include pre-flight tasks
  ansible.builtin.import_tasks: pre-flight.yml

- name: check if composes.yml exists
  ansible.builtin.stat:
    path: "/var/www/html/{{ builder_blueprint_name }}.yml"
  register: composes_file

- name: attempt to read in composed images
  when:
    - composes_file.stat.exists
  block:
    - name: slurp up composes.yml file
      ansible.builtin.slurp:
        src: "/var/www/html/{{ builder_blueprint_name }}.yml"
      register: available_images_raw
      
    - name: set available_images fact
      ansible.builtin.set_fact:
        available_images: "{{ available_images_raw['content'] | b64decode | from_yaml }}" 

# - debug:
#     msg: "{{ builder_rhsm_repos }}"

- name: run infra.osbuild.builder role and capture the output
  when:
    - not composes_file.stat.exists or
      image.version not in available_images|json_query('[*].version')|list
  block:
    - name: run the image builder role
      ansible.builtin.include_role:
        name: infra.osbuild.builder
    - name: include post-flight tasks
      ansible.builtin.include_tasks: post-flight.yml
