---

- name: import /etc/hosts tasks
  ansible.builtin.import_tasks: etc-hosts.yml

- name: import hostname tasks
  ansible.builtin.import_tasks: hostname.yml

- name: import packages tasks
  ansible.builtin.import_tasks: packages.yml

- name: import firewalld tasks
  ansible.builtin.import_tasks: firewalld.yml

- name: import lingering tasks
  ansible.builtin.import_tasks: lingering.yml

- name: import ssh-keypair tasks
  ansible.builtin.import_tasks: ssh-keypair.yml

- name: import selinux tasks
  ansible.builtin.import_tasks: selinux.yml

- name: Import python libraries tasks
  ansible.builtin.import_tasks: python-libraries.yml
