---

- name: push config files
  ansible.builtin.template:
    src: "templates/{{ template.src }}.j2"
    dest: "{{ template.dest }}"
  loop: "{{ local_dns_config_files }}"
  loop_control:
    loop_var: template
  notify:
    - restart_services

- name: initialize hosts file
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.hosts
    line: '{{ ansible_default_ipv4.address }} edge-manager.{{ local_dns_domain }}'
    create: true
    insertafter: EOF
