---

- name: enable ip forwarding now
  ansible.builtin.shell:
    cmd: echo '1' > /proc/sys/net/ipv4/ip_forward
  listen:
    - enable_ip_forwarding

- name: restart services
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: restarted
  loop: "{{ wireless_ap_services }}"
  loop_control:
    loop_var: service
  listen:
    - restart_services
