---

# List of local services
#  - dhcp
#  - dns
#  - gitea
#  - eda
# 
# - name: attempt to load in vars for workshop
#   ansible.builtin.include_vars:
#     file: "workshop_vars/{{ workshop_type }}.yml"
    
- name: Set fact with internal_address
  set_fact:
    internal_address: "{{ item.templates[0].vars.internal_address }}"
  with_items: "{{ local_services }}"
  when: "'dnsmasq' in item.name" 

- name: create build dir
  ansible.builtin.file:
    path: "{{ build_dir }}"
    state: directory

- name: loop through builds
  ansible.builtin.include_tasks:
    file: build-container.yml
    apply:
      become: "{{ service.privileged | default('false') }}"
  loop: "{{ services }}"
  loop_control:
    loop_var: service

