---
- name: Gather Red Hat Subscription Facts
  shell: subscription-manager status | grep Overall | awk '{print $3}'
  changed_when: false
  register: subscription_facts
  ignore_errors: true

- name: If system already registered
  when:
    - "subscription_facts.stdout == 'Current' or
      subscription_facts.stdout == 'Disabled'"
  block:
    - name: Print status
      ansible.builtin.debug:
        msg: "System is already subscribed"
    - name: Set registration fact
      ansible.builtin.set_fact:
        _register_system: false

# This is not working for the AWS node
#    - name: register to the customer portal
#      community.general.redhat_subscription:
#        username: "{{ redhat_username }}"
#        password: "{{ redhat_password }}"
#        force_register: true
#      notify:
#        - clean_dnf
#      when: "subscription_facts.stdout != 'Current'"

- name: Register and attach the node
  shell: "subscription-manager register --username {{ redhat_username }} --password {{ redhat_password }} --force ; subscription-manager attach --auto"
  notify:
    - clean_dnf
  when:
    - _register_system
  register: _registration_info

- name: Display subscription facts after subscribing
  shell: subscription-manager status | grep Overall | awk '{print $3}'
  register: subscription_facts_after
  when:
    - _registration_info.changed
