---

top_line_variables:
  type: demo
  name: sps_2023

local_services:
  - name: dnsmasq
    privileged: true
    templates:
      - src: dnsmasq.conf.j2
        dest: dnsmasq.conf
        vars:
          upstream_dns_servers:
            - 8.8.8.8
            - 8.8.4.4
          internal_address: 192.168.1.1
          internal_netmask: 24
          dhcp_range_start: 192.168.1.5
          dhcp_range_end: 192.168.1.254
          dhcp_lease_time: 12h
      - src: dnsmasq.hosts.j2
        dest: dnsmasq.hosts
        vars:
          dns_entries:
            - record: "controller.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "image-builder.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "gitea.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "attendance.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "ipxe.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "ostree-repo.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "exercises.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "attendance.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "eda.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
    post_tasks:
      - dnsmasq-update-etc-hosts.yml
    containerfile: dnsmasq-containerfile
  - name: reverse-proxy
    containerfile: reverse-proxy-containerfile
    pre_tasks:
      - reverse-proxy-copy-certs.yml
    templates:
      - src: reverse-proxy-nginx.conf.j2
        dest: nginx.conf
        vars:
          proxied_services:
            - name: controller
              proxy_pass: "https://localhost:10443/"
              proxy_advanced_options:
                - proxy_ssl_verify off
            - name: image-builder
              proxy_pass: "https://localhost:9090/"
              web_socket: true
              proxy_advanced_options:
                - proxy_ssl_verify off
            - name: gitea
              proxy_pass: "http://localhost:3001/"
            - name: ostree-repo
              proxy_pass: "http://localhost:18080/"
            - name: attendance
              proxy_pass: "http://localhost:3000/"
              web_socket: true
            - name: eda
              proxy_pass: "http://localhost:5000/"
            - name: ipxe
              proxy_pass: "http://localhost:8081/"
  - name: database
    containerfile: database-containerfile
    templates:
      - src: database-postgresql.conf.j2
        dest: postgresql.conf
      - src: database-db-start.sh.j2
        dest: db-start.sh
        vars:
          databases:
            - name: gitea
              username: gitea
              password: gitea
  - name: gitea
    containerfile: gitea-containerfile
    templates:
      - src: gitea-app.ini.j2
        dest: app.ini
  - name: attendance
    containerfile: attendance-containerfile
    pre_tasks:
      - attendance-student-pages.yml
      - attendance-rsync-site.yml
    templates:
      - src: attendance-App.js.j2
        dest: attendance/src/App.js
      - src: attendance-index.js.j2
        dest: attendance/src/pages/index.js
  - name: tftp
    containerfile: tftp-containerfile
    pre_tasks:
      - tftp-download-chainload-files.yml
  - name: ostree-repo
    containerfile: ostree-repo-containerfile
    pre_tasks:
      - ostree-repo-copy-repo.yml
    files:
      - src: ostree-repo-nginx.conf
        dest: nginx.conf
  - name: ipxe
    containerfile: ipxe-containerfile
    pre_tasks:
      - ipxe-get-boot-iso.yml
      - ipxe-dcn-kickstart.yml
    post_tasks:
      - ipxe-cleanup-boot-iso.yml
    templates:
      - src: workshop.ipxe.j2
        dest: workshop.ipxe
    files:
      - src: ipxe-nginx.conf
        dest: nginx.conf
  - name: eda
    containerfile: eda-containerfile
    templates:
      - src: eda-run-workflow.yml.j2
        dest: run-workflow.yml
    files:
      - src: eda-rulebook.yml
        dest: rulebook.yml
      - src: eda-inventory.yml
        dest: inventory.yml
      - src: eda-ansible.cfg
        dest: ansible.cfg
pods:
  - name: "{{ top_line_variables.type }}-{{ top_line_variables.name }}-priv"
    privileged: true
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          # should make these vars at some point
          io.podman.annotations.autoremove/demo-sps_2023-priv: "FALSE"
          io.podman.annotations.init/demo-sps_2023-priv: "FALSE"
          io.podman.annotations.privileged/demo-sps_2023-priv: "TRUE"
          io.podman.annotations.publish-all/demo-sps_2023-priv: "FALSE"
        labels:
          app: "{{ top_line_variables.type }}-{{ top_line_variables.name }}-priv"
        name: "{{ top_line_variables.type }}-{{ top_line_variables.name }}-priv"
      spec:
        hostNetwork: true
        containers:
          - name: dnsmasq
            image: dnsmasq:latest
            securityContext:
              privileged: true
  - name: "{{ top_line_variables.type }}-{{ top_line_variables.name }}"
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          io.podman.annotations.autoremove/demo-sps_2023: "FALSE"
          io.podman.annotations.init/demo-sps_2023: "FALSE"
          io.podman.annotations.privileged/demo-sps_2023: "FALSE"
          io.podman.annotations.publish-all/demo-sps_2023: "FALSE"
        labels:
          app: "{{ top_line_variables.type }}-{{ top_line_variables.name }}"
        name: "{{ top_line_variables.type }}-{{ top_line_variables.name }}"
      spec:
        hostNetwork: true
        containers:
          - name: reverse-proxy
            image: reverse-proxy:latest
          - name: database
            image: database:latest
            volumeMounts:
              - mountPath: /var/lib/pgsql/data
                name: database-data
          - name: gitea
            image: gitea:latest
          - name: attendance
            image: attendance:latest
          - name: tftp
            image: tftp:latest
          - name: ostree-repo
            image: ostree-repo:latest
          - name: ipxe
            image: ipxe:latest
          - name: eda
            image: eda:latest
        volumes:
          - name: database-data
            persistentVolumeClaim:
              claimName: "{{ top_line_variables.type }}-{{ top_line_variables.name }}-database"

pre_flight_roles:
  - reposync_repo

repos_to_sync:
  - rhel-9-for-x86_64-highavailability-rpms

builder_blueprint_name: rhde-image
images_to_compose:
  # Blank image
  - version: 1.0.0
    type: edge-commit
    packages:
      - vim-enhanced
      - git
      - nano
      - NetworkManager-wifi
      - podman
      - pcs
      - pacemaker
    customizations:
      files:
        - path: /etc/containers/containers.conf
          mode: '0644'
          user: root
          group: root
          data: "[engine]\nruntime='crun'"
    custom_repos:
      - name: ha-localsync
        base_url: file:///opt/reposync/rhel-9-for-x86_64-highavailability-rpms
        type: yum-baseurl
        check_ssl: false
        check_gpg: false
        state: present

image_builder_http_port: 11080

install_gitea: false
gitea_demo_user: ot-operator
gitea_repo_name: dcn-codebase
gitea_container: "{{ top_line_variables.type }}-{{ top_line_variables.name }}-gitea"
repo_files:
  - src: templates/sps_2023/README.md.j2
    dest: README.md
  - src: templates/sps_2023/hello-world.yml.j2
    dest: playbooks/hello-world.yml
  - src: templates/sps_2023/manage-hosts-in-controller.yml.j2
    dest: playbooks/manage-hosts-in-controller.yml
  - src: templates/sps_2023/setup-pacemaker-cluster.yml.j2
    dest: playbooks/setup-pacemaker-cluster.yml

allowed_external_services:
  - port: 5000
  - port: 8081
  - port: 10443
  - port: 9090
  - port: 3001
  - port: 3000
  - port: 80
  - port: 443
