---

- name: Create namespace for operator install
  redhat.openshift.k8s:
    definition: "{{ _namespace }}"

- name: Create operator group
  redhat.openshift.k8s:
    template: templates/operatorgroup.yaml.j2

- name: Install operator
  redhat.openshift.k8s:
    definition: "{{ _subscription }}"

- name: Create instance of controller
  redhat.openshift.k8s:
    template: templates/automationcontroller.yaml.j2
  register: _instance_deploy
  until:
    - not _instance_deploy.failed
  retries: 30
  delay: 30
