---

- name: allow overriding of s3 bucket name
  ansible.builtin.set_fact:
    s3_bucket_name: "{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone|lower }}.private"
  when:
    - s3_bucket_name is not defined

- name: s3 bucket for persistent storage of ec2 key exists
  amazon.aws.s3_bucket:
    name: "{{ s3_bucket_name }}"
    state: present
    region: "{{ ec2_region }}"
    tags:
      ansible-workshops: "true"
  retries: 4
  delay: 15
  register: s3_result
  until: s3_result.failed == false

- name: Store SSH Key Pair
  amazon.aws.aws_s3:
    bucket: "{{ s3_bucket_name }}"
    mode: put
    object: "{{ec2_name_prefix}}-private.pem"
    src: "{{ workshop_folder }}/ssh-key.pem"
    encrypt: true
    region: "{{ ec2_region }}"
  when: create_key.changed

- name: Save Private key from S3 Bucket when not generating it
  amazon.aws.aws_s3:
    bucket: "{{ s3_bucket_name }}"
    mode: get
    object: "{{ ec2_name_prefix }}-private.pem"
    dest: "{{ workshop_folder }}/ssh-key.pem"
    encrypt: true
    region: "{{ ec2_region }}"
  when: not create_key.changed
