apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
spec:
  host: dashboard.192.168.3.101.nip.io
  port:
    targetPort: 3000
  to:
    kind: Service
    name: grafana
    weight: 100
  wildcardPolicy: None