name = "iot-gateway-3.0.0"
description = "IoT Gateway Blueprint w/ RHDE"
version = "3.0.0"
modules = []
groups = []

[[packages]]
name = "cockpit"
version = "*"

[[packages]]
name = "qemu-kvm"
version = "*"

[[packages]]
name = "libvirt"
version = "*"

[[packages]]
name = "virt-install"
version = "*"

[[packages]]
name = "virt-viewer"
version = "*"

[[packages]]
name = "microshift"
version = "*"

[[packages]]
name = "microshift-gitops"
version = "*"

[[packages]]
name = "microshift-olm"
version = "*"

[[packages]]
name = "pcp"
version = "*"

[[packages]]
name = "pcp-zeroconf"
version = "*"

[[packages]]
name = "skupper-cli"
version = "*"

[[packages]]
name = "openshift-clients"
version = "*"

[[packages]]
name = "cronie"
version = "*"

[[packages]]
name = "cronie-anacron"
version = "*"

[[packages]]
name = "python3-pip"
version = "*"

[[packages]]
name = "python3-kubernetes"
version = "*"

[[packages]]
name = "NetworkManager-wifi"
version = "*"

[[packages]]
name = "ansible-core"
version = "*"

[[packages]]
name = "ostree"
version = "*"

[[packages]]
name = "rpm-ostree"
version = "*"

[[packages]]
name = "avahi"
version = "*"

[[packages]]
name = "git"
version = "*"

[[packages]]
name = "iputils"
version = "*"

[[packages]]
name = "bind-utils"
version = "*"

[[packages]]
name = "net-tools"
version = "*"

[[packages]]
name = "iotop"
version = "*"

[[packages]]
name = "pcp"
version = "*"

[[packages]]
name = "redhat-release"
version = "*"

[customizations]
hostname = "microshift-node"

[customizations.services]
enabled = ["cockpit", "libvirtd", "crio", "microshift","rpm-ostreed","pmcd"]
hostname = "microshift-node"

[customizations.firewall]
ports = ["22:tcp", "9090:tcp", "80:tcp", "443:tcp", "6443:tcp", "5353:udp","11111:udp","8889:udp","8890:udp"]

[[customizations.sshkey]]
user = "root"
key = ""

[[customizations.user]]
name = "redhat"
description = "Admin user"
password = '<password hash obatained with: python3 -c 'import crypt,getpass;pw=getpass.getpass();print(crypt.crypt(pw) if (pw==getpass.getpass("Confirm: ")) else exit())' >'
key = ""
home = "/home/redhat/"
shell = "/usr/bin/bash"
groups = ["users", "wheel"]

[[containers]]
source = "quay.io/yono/dgw:3.3.0-amd64"


[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d1bf14b71f6ec4155dfb77b832fab64c39da616e1cff803e70efdcdb8e43d48b"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:983825a81bf8ac728106d422adf6fff55a1c0daef5269ba90509a9de3cdc0d36"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e3573c10e9a398fcd0cbbf00abcfa221c6b4f1cde23f498698e3a01a8965bd0c"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5b531ec7f933ae84539a51008057f354ef45ed6b869a939aaef1e5e8d35cdeef"

[[containers]]
source = "registry.redhat.io/ubi9@sha256:ed84f34cd929ea6b0c247b6daef54dd79602804a32480a052951021caf429494"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b3275cfe65e96a226b170eca1852b1346c3e4c2b59e1a7d021591f3309efbf65"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4fda2303083e894e928ee6bfb05822fed6d6e713bc174b89e9ba2aee2c3a58b9"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f1825699b341e19a2b0e5b33f6cba854b7e0a588ab419870624041fbca00122a"

[[containers]]
source = "registry.redhat.io/lvms4/topolvm-rhel9@sha256:ce0c78c2867fb0b73c4911ae6afd5aaf9a413480cfcf4f31f46f2387c3df97e0"

[[containers]]
source = "registry.redhat.io/openshift4/ose-csi-node-driver-registrar@sha256:95691c21198e20d11777d592806fa00c018c17443d9b3aee853891dac6090470"

[[containers]]
source = "registry.redhat.io/openshift4/ose-csi-livenessprobe@sha256:98ad03919da81c910aaa8a4f12fcae3048f2119735aeb7ca5271f7c16cf5e4e6"

[[containers]]
source = "registry.redhat.io/openshift4/ose-csi-external-resizer@sha256:94f4a9ad37891cfbf58ca7db58000e703ff4d9d7a7b207d50ec844c1610e2111"

[[containers]]
source = "registry.redhat.io/openshift4/ose-csi-external-provisioner@sha256:76a5646d4b8406ae9065a1605644ec641acc97aa471ebae744e8e06487cec765"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b4d054b21be4bbc3781b93489faacf84c3db4b99bb7abc0effb42947f19ffc92"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7bb61586d06de622c1bb4edf34971a91683620eaae65c7e1544ffee2a52d525d"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b6c1cbdd6a01b555608fb0bfbcf73fcc1c8241b56620ee4e14d5b50564548e39"

