name = "rhde-microshift-1.0.1"
description = "RHDE w/ Microshift Blueprints"
version = "1.0.1"
modules = []
groups = []

[[packages]]
name = "microshift"
version = "*"

[[packages]]
name = "openshift-clients"
version = "*"

[[packages]]
name = "subscription-manager"
version = "*"

[[packages]]
name = "cronie"
version = "*"

[[packages]]
name = "cronie-anacron"
version = "*"

[[packages]]
name = "python3-pip"
version = "*"

[[packages]]
name = "python3-kubernetes"
version = "*"

[[packages]]
name = "subscription-manager"
version = "*"

[[packages]]
name = "NetworkManager-wifi"
version = "*"

[[packages]]
name = "ansible-core"
version = "*"

[[packages]]
name = "ostree"
version = "*"

[[packages]]
name = "rpm-ostree"
version = "*"

[[packages]]
name = "avahi"
version = "*"

[[packages]]
name = "git"
version = "*"

[[packages]]
name = "iputils"
version = "*"

[[packages]]
name = "bind-utils"
version = "*"

[[packages]]
name = "net-tools"
version = "*"

[[packages]]
name = "iotop"
version = "*"

[[packages]]
name = "redhat-release"
version = "*"

[[containers]]
source = "quay.io/yono/dgw:3.3.0-amd64"

[customizations]
hostname = "microshift-node"

[customizations.services]
enabled = ["crio", "microshift"]
hostname = "microshift-node"

[customizations.firewall]
ports = ["22:tcp", "80:tcp", "443:tcp", "6443:tcp", "5353:udp"]

[[customizations.sshkey]]
user = "root"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWMsj1B8fOaOTDZWAH5EmM4b835I/JBpAz73v15GuUuKEcHxEZOHF3ghchYWq0dwgtqXTdwWsZRyuDhd4LF69WIcodcwRZRqOXMRYsnQ6376ynM2Q+MCtDNBD0DzJpqfCM5qEFIzG8SMmQzrpISTkQ9iDTPf0iMkfZuIhjrtR44+YG9AfU/C9SSHIjIjxxvszIx7X32S0kuQnBi6kg2N5e4Hm9il7CVYjMLbAkMbh6aLqb1lPbX3mNsoRS36xyuaOW4Ai1eooKhmcOZ1Xam3JaC1oMiLPWJmNq9Hlanxh55wjP49RGPK+Gnwir5GUG4iPcP0o7Qe/FeXG16wildCOw0QAYdUNT94oMRXZbN/t8hZ1XTDt3tvVOIun4zUgDLgtNx2J+JZBB4UyLhcXi0clnlY8rGG+DSYGrcOJugqSwX4FZVwjxc/4LB0rVRAZd8BOp7LmUsv/QB1pCpZ9ufhmDJDmhB1Q8A5gMWS+hNUIVXXLgfuyhS4ojPw5LZ4QNYuU= redhat@edge-management.local"

[[customizations.user]]
name = "redhat"
description = "Admin user"
password = '$6$B495skea5D5l4ob0$KzPsTMi5nqQEpi7Zq3zAYuu.LXGARbO3ZoCEBl0DciEc.aXbQ9iN8GrlQh6DRSMWuMPFCNEIYwpneSy3wI.fT/'
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWMsj1B8fOaOTDZWAH5EmM4b835I/JBpAz73v15GuUuKEcHxEZOHF3ghchYWq0dwgtqXTdwWsZRyuDhd4LF69WIcodcwRZRqOXMRYsnQ6376ynM2Q+MCtDNBD0DzJpqfCM5qEFIzG8SMmQzrpISTkQ9iDTPf0iMkfZuIhjrtR44+YG9AfU/C9SSHIjIjxxvszIx7X32S0kuQnBi6kg2N5e4Hm9il7CVYjMLbAkMbh6aLqb1lPbX3mNsoRS36xyuaOW4Ai1eooKhmcOZ1Xam3JaC1oMiLPWJmNq9Hlanxh55wjP49RGPK+Gnwir5GUG4iPcP0o7Qe/FeXG16wildCOw0QAYdUNT94oMRXZbN/t8hZ1XTDt3tvVOIun4zUgDLgtNx2J+JZBB4UyLhcXi0clnlY8rGG+DSYGrcOJugqSwX4FZVwjxc/4LB0rVRAZd8BOp7LmUsv/QB1pCpZ9ufhmDJDmhB1Q8A5gMWS+hNUIVXXLgfuyhS4ojPw5LZ4QNYuU= redhat@edge-management.local"
home = "/home/redhat/"
shell = "/usr/bin/bash"
groups = ["users", "wheel"]
