apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: amq-broker
  name: amq-broker-datavol-amq-broker-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem