---

local_services:
  - name: dnsmasq
    privileged: true
    templates:
      - src: dnsmasq.conf.j2
        dest: dnsmasq.conf
        vars:
          upstream_dns_servers:
            - 8.8.8.8
            - 8.8.4.4
          internal_address: 192.168.1.1
          internal_netmask: 24
          dhcp_range_start: 192.168.1.5
          dhcp_range_end: 192.168.1.254
          dhcp_lease_time: 12h
      - src: dnsmasq.hosts.j2
        dest: dnsmasq.hosts
        vars:
          dns_entries:
            - record: "ipxe.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "controller.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "image-builder.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "gitea.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "eda.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "ostree-repo.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "attendance.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
            - record: "exercises.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
              address: "{{ internal_address }}"
          dhcp_reservations:
            - mac_address: 'e4:90:69:a2:b7:41'
              ip_address: 192.168.1.141
              name: plc
            - mac_address: 'e4:90:69:a2:b7:42'
              ip_address: 192.168.1.142
              name: drive
    post_tasks:
      - dnsmasq-update-etc-hosts.yml
    containerfile: dnsmasq-containerfile
  - name: eda
    containerfile: eda-containerfile
    templates:
      - src: eda-run-workflow.yml.j2
        dest: run-workflow.yml
    files:
      - src: eda-rulebook.yml
        dest: rulebook.yml
      - src: eda-inventory.yml
        dest: inventory.yml
      - src: eda-ansible.cfg
        dest: ansible.cfg
  - name: reverse-proxy
    containerfile: reverse-proxy-containerfile
    pre_tasks:
      - reverse-proxy-copy-certs.yml
    templates:
      - src: reverse-proxy-nginx.conf.j2
        dest: nginx.conf
        vars:
          proxied_services:
            - name: eda
              proxy_pass: "http://localhost:5000/"
            - name: ipxe
              proxy_pass: "http://localhost:8081/"
            - name: controller
              proxy_pass: "https://localhost:10443/"
              proxy_advanced_options:
                - proxy_ssl_verify off
            - name: image-builder
              proxy_pass: "https://localhost:9090/"
              web_socket: true
              proxy_advanced_options:
                - proxy_ssl_verify off
            - name: gitea
              proxy_pass: "http://localhost:3001/"
            - name: ostree-repo
              proxy_pass: "http://localhost:8080/"
            - name: attendance
              proxy_pass: "http://localhost:3000/"
              web_socket: true
            - name: exercises
              proxy_pass: https://redhat-manufacturing.github.io/device-edge-workshops/exercises/rhde_tse/
  - name: ipxe
    containerfile: ipxe-containerfile
    pre_tasks:
      - ipxe-get-boot-iso.yml
      - ipxe-student-kickstarts.yml
    post_tasks:
      - ipxe-cleanup-boot-iso.yml
    templates:
      - src: workshop.ipxe.j2
        dest: workshop.ipxe
    files:
      - src: ipxe-nginx.conf
        dest: nginx.conf
  - name: database
    containerfile: database-containerfile
    templates:
      - src: database-postgresql.conf.j2
        dest: postgresql.conf
      - src: database-db-start.sh.j2
        dest: db-start.sh
        vars:
          databases:
            - name: gitea
              username: gitea
              password: gitea
            - name: attendance
              username: attendance
              password: attendance
  - name: gitea
    containerfile: gitea-containerfile
    templates:
      - src: gitea-app.ini.j2
        dest: app.ini
  - name: tftp
    containerfile: tftp-containerfile
    pre_tasks:
      - tftp-download-chainload-files.yml
  - name: ostree-repo
    containerfile: ostree-repo-containerfile
    pre_tasks:
      - ostree-repo-copy-repo.yml
    files:
      - src: ostree-repo-nginx.conf
        dest: nginx.conf
  - name: attendance
    containerfile: attendance-containerfile
    pre_tasks:
      - attendance-student-pages.yml
      - attendance-rsync-site.yml
    templates:
      - src: attendance-App.js.j2
        dest: attendance/src/App.js
      - src: attendance-index.js.j2
        dest: attendance/src/pages/index.js
      


pods:
  - name: workshop-rhde_tse-priv
    privileged: true
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          io.podman.annotations.autoremove/workshop-rhde_tse-priv: "FALSE"
          io.podman.annotations.init/workshop-rhde_tse-priv: "FALSE"
          io.podman.annotations.privileged/workshop-rhde_tse-priv: "TRUE"
          io.podman.annotations.publish-all/workshop-rhde_tse-priv: "FALSE"
        labels:
          app: workshop-rhde_tse-priv
        name: workshop-rhde_tse-priv
      spec:
        hostNetwork: true
        containers:
          - name: dnsmasq
            image: dnsmasq:latest
            securityContext:
              privileged: true
  - name: workshop-rhde_tse
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          io.podman.annotations.autoremove/workshop-rhde_tse: "FALSE"
          io.podman.annotations.init/workshop-rhde_tse: "FALSE"
          io.podman.annotations.privileged/workshop-rhde_tse: "FALSE"
          io.podman.annotations.publish-all/workshop-rhde_tse: "FALSE"
        labels:
          app: workshop-rhde_tse
        name: workshop-rhde_tse
      spec:
        hostNetwork: true
        containers:
          - name: reverse-proxy
            image: reverse-proxy:latest
          - name: eda
            image: eda:latest
          - name: ipxe
            image: ipxe:latest
          - name: database
            image: database:latest
            volumeMounts:
              - mountPath: /var/lib/pgsql/data
                name: database-data
          - name: gitea
            image: gitea:latest
          - name: tftp
            image: tftp:latest
          - name: ostree-repo
            image: ostree-repo:latest
          - name: attendance
            image: attendance:latest
        volumes:
          - name: database-data
            persistentVolumeClaim:
              claimName: workshop-rhde_tse-database

builder_blueprint_name: rhde-image
images_to_compose:
  - version: 1.0.0
    type: edge-commit
    packages:
      - vim-enhanced
      - git
      - nano
      - NetworkManager-wifi
      - podman
image_builder_http_port: 11080

skip_builder_services: true

install_gitea: false
gitea_container: workshop-rhde_tse-gitea
repo_files:
  - src: templates/README.md.j2
    dest: README.md
  - src: templates/hello-world.yml.j2
    dest: playbooks/hello-world.yml
  - src: templates/rhde_tse/manage-hosts-in-controller.yml.j2
    dest: playbooks/manage-hosts-in-controller.yml
  - src: templates/rhde_tse/initial-configuration.yml.j2
    dest: playbooks/initial-configuration.yml

allowed_external_services:
  - port: 5000
  - port: 8081
  - port: 10443
  - port: 9090
  - port: 3001
  - port: 8080
  - port: 3000
  - port: 80
  - port: 443
