---

workshop_customer_portal_downloads:
  - file: rhel-8-boot.iso
    sha256: 47e5dbb37b5970f583d0852973af86cc1b522ee1f1e2374c59204583c14717fa

workshop_controller_ee: quay.io/device-edge-workshops/provisioner-execution-environment:latest

builder_blueprint_name: rhde-image

builder_compose_customizations:
  user:
    name: ansible
    description: ansible
    password: "{{ admin_password }}"
    groups: '["users", "wheel"]'

images_to_compose:
  - version: 1.0.0
    type: edge-commit
    packages:
      - vim-enhanced
      - git
      - nano
      - NetworkManager-wifi
      - ansible-core
  - version: 2.0.0
    type: edge-commit
    repos:
      - name: EPEL8
        base_url: "https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/"
        type: yum-baseurl
        check_ssl: true
        check_gpg: false
    packages:
      - vim-enhanced
      - git
      - nano
      - mosquitto
      - nodejs
      - NetworkManager-wifi
      - ansible-core
  - version: 3.0.0
    type: edge-commit
    repos:
      - name: EPEL8
        base_url: "https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/"
        type: yum-baseurl
        check_ssl: true
        check_gpg: false
        state: absent
    packages:
      - vim-enhanced
      - git
      - nano
      - podman
      - buildah
      - skopeo
      - NetworkManager-wifi
      - ansible-core
  # - version: 4.0.0
  #   type: edge-commit
  #   repos:
  #     - name: microshift
  #       base_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/microshift/ocp-dev-preview/latest-4.12/el8/os/
  #       type: yum-baseurl
  #       check_ssl: true
  #       check_gpg: false
  #     - name: microshift-deps
  #       base_url: https://download.copr.fedorainfracloud.org/results/@redhat-et/microshift-testing/epel-8-x86_64/
  #       type: yum-baseurl
  #       check_ssl: true
  #       check_gpg: false
    # packages:
    #   - vim-enhanced
    #   - git
    #   - nano
    #   - microshift
    #   - NetworkManager-wifi
    #   - ansible-core
