apiVersion: v1
kind: ConfigMap
metadata:
  name: oee-handler-config
  namespace: cps
data:
  PUB_TOPIC: "oee"
  SUB_TOPIC: "result"
  MQTT_BROKER_ADDRESS: "amq-broker-hdls-svc"
  MQTT_PORT: "61616"
  KAFKA_USE: "" # NULL -> MQTT mode, True -> Kafka mode
  KAFKA_BOOTSTRAP_SERVER: "my-cluster-kafka-bootstrap.demo:9092"
  PER_CYCLES: "3"
  DESIRED_CYCLE_WINDOW: "60.0"
  DESIRED_PRODUCTION_NUMBER: "1"
  DEBUG: "" # NULL -> False, True -> output debug log