apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: oee-handler
  labels:
    app: oee-handler
  name: oee-handler
  namespace: cps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oee-handler
  strategy: {}
  template:
    metadata:
      annotations:
        app: oee-handler
      labels:
        app: oee-handler
    spec:
      containers:
      - image: registry.gitlab.com/yono1/cps-demo/oee-handler:v1.0
        imagePullPolicy: IfNotPresent
        name: oee-handler
        envFrom:
          - configMapRef:
              name: oee-handler-config
      restartPolicy: Always