---

- name: create DNS record for hypervisor
  become: false
  community.aws.route53:
    state: "{{ s3_state }}"
    zone: "{{ workshop_dns_zone }}"
    record: "{{ inventory_hostname }}.{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}"
    type: A
    overwrite: true
    value: "{{ ansible_host }}"
    wait: true
    access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: route53_status
