---

- name: install virt module
  ansible.builtin.dnf:
    name: "{{ _kvm_packages }}"
  register: virt_installed

- name: start/enable services
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true

- name: run virt host validater
  ansible.builtin.shell:
    cmd: virt-host-validate
  register: virt_host_validate_output
  when:
    - virt_installed.changed
  
- name: create storage directory for VMs
  ansible.builtin.file:
    path: /var/virtual-machines
    state: directory
    owner: qemu
    group: qemu

- name: create storage directory for student ISOs
  ansible.builtin.file:
    path: /var/virtual-machines/iso
    state: directory
    owner: qemu
    group: qemu
