---

- name: Add shortnames to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: EOF
    line: "192.168.122.{{ 10 + student_number }} student{{ student_number }}-edge-device"
  loop: "{{ range(1, (student_total + 1), 1)|list }}"
  loop_control:
    loop_var: student_number
