---

- name: create ACME account
  community.crypto.acme_account:
    account_key_src: "{{ _cert_dir }}/{{ domain_name_short }}.account.key"
    acme_directory: https://acme.zerossl.com/v2/DV90
    acme_version: 2
    external_account_binding:
      alg: "{{ zerossl_account.alg }}"
      key: "{{ zerossl_account.key }}"
      kid: "{{ zerossl_account.kid }}"
    state: present
    contact:
      - mailto:ansible-network@redhat.com
    request_timeout: 120
  register: acme_account
  retries: 10
  delay: 30
  until: not acme_account.failed

- name: create challenge for {{ domain_name }}
  community.crypto.acme_certificate:
    account_uri: "{{ acme_account.account_uri }}"
    account_key_src: "{{ _cert_dir }}/{{ domain_name_short }}.account.key"
    acme_directory: https://acme.zerossl.com/v2/DV90
    acme_version: 2
    csr: "{{ _cert_dir }}/{{ domain_name_short }}.csr"
    dest: "{{ _cert_dir }}/{{ domain_name_short }}.crt"
    challenge: dns-01
    request_timeout: 120
  register: dns_challenge
  retries: 10
  delay: 30
  until: not dns_challenge.failed
