---

- name: validate challenge
  community.crypto.acme_certificate:
    account_uri: "{{ acme_account.account_uri }}"
    account_key_src: "{{ _cert_dir }}/{{ domain_name_short }}.account.key"
    src: "{{ _cert_dir }}/{{ domain_name_short }}.csr"
    cert: "{{ _cert_dir }}/{{ domain_name_short }}.crt"
    fullchain: "{{ _cert_dir }}/{{ domain_name_short }}-fullchain.crt"
    chain: "{{ _cert_dir }}/{{ domain_name_short }}-intermediate.crt"
    challenge: dns-01
    acme_directory: https://acme.zerossl.com/v2/DV90
    acme_version: 2
    data: "{{ dns_challenge }}"
    request_timeout: 120
  register: issue_cert
  retries: 10
  delay: 30
  until: not issue_cert.failed
