---

- name: ensure permissions are correct
  ansible.builtin.file:
    path: "{{ _cert_dir }}"
    recurse: true
    owner: "{{ _cert_owner }}"
    group: "{{ _cert_group }}"


- name: Cleanup challenges
  become: false
  community.aws.route53:
    state: absent
    zone: "{{ workshop_dns_zone }}"
    record: "{{ _challenge_data_dns.key }}"
    type: TXT
    value: "{{ _challenge_data_dns.value.0 | regex_replace('^(.*)$', '\"\\1\"') }}"
    wait: true
  delegate_to: localhost
  register: route53_status
  loop: "{{ lookup('ansible.builtin.dict', dns_challenge.challenge_data_dns, wantlist=True) }}"
  loop_control:
    loop_var: _challenge_data_dns
  when:
    - dns_challenge.challenge_data_dns is defined
