---

- name: enable lingering for 
  ansible.builtin.shell:
    cmd: loginctl enable-linger 
  args:
    creates: "/var/lib/systemd/linger/"
  become: true

- name: push out yaml
  ansible.builtin.template:
    src: templates/process-control.yaml.j2
    dest: "/home//process-control.yaml"

- name: podman play kube
  containers.podman.podman_play:
    kube_file: "/home//process-control.yaml"
    state: started
  register: app_deployed

- name: wait for app startup
  ansible.builtin.wait_for:
    port: 1881
  when:
    - app_deployed.changed

- name: allow 1881 through the firewall
  ansible.posix.firewalld:
    port: 1881/tcp
    zone: public
    permanent: true
    state: enabled
    immediate: true
  become: true