---

- name: setup for edge-management node
  block:
    - name: find ami for edge-management node
      ec2_ami_info:
        region: "{{ ec2_region }}"
        owners: "{{ ec2_info['edge-management'].owners }}"
        filters:
          name: "{{ ec2_info['edge-management'].filter }}"
          architecture: "{{ ec2_info['edge-management'].architecture }}"
      register: edge_management_node_amis

    - name: save ami for node for edge-management node
      set_fact:
        edge_management_node_ami: >
          {{ amis.images | selectattr('name', 'defined') | sort(attribute='name') | last }}

- name: common tasks
  block:
    - name: ensure at least RHEL9.1+
      ansible.builtin.assert:
        that:
          - edge_management_node_ami.name[5] | int >= 9
          - edge_management_node_ami.name[7] | int >= 1
        msg: "Please use RHEL9.1 or later"
