---

- name: create dir for kickstarts
  ansible.builtin.file:
    path: "{{ build_dir }}/ipxe/kickstarts"
    state: directory

- name: template out kickstarts
  ansible.builtin.template:
    src: "templates/{{ workshop_type }}/ipxe-student-kickstart.ks.j2"
    dest: "{{ build_dir }}/ipxe/kickstarts/student{{ student_number }}.ks"
  loop: "{{ range(1, (student_total + 1), 1)|list }}"
  loop_control:
    loop_var: student_number
