apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- argocd-crd.yaml
- argocd-cluster.yaml
- argocd-apps.yaml
- argocd-rolebinding.yaml
- argocd-clusterrolebinding.yaml
- argocd-application.yaml
