---
 - hosts: all
   tasks:
   - name: Install requirements for device management system
     ansible.builtin.dnf:
       name:
         - git
         - createrepo
         - yum-utils
         - lorax
         - skopeo
         - runc
         - composer-cli
         - cockpit-composer
         - cockpit-podman
         - libvirt
         - virt-manager
         - virt-viewer
         - libvirt-client
         - podman
         - jq
         - wget
         - qemu-kvm
         - qemu-img
         - genisoimage
         - syslinux
         - isomd5sum
         - avahi
       state: latest
     become: true

   - name: Enable and start cockpit.socket
     ansible.builtin.service:
       name: cockpit.socket
       enabled: yes
       state: started
     become: true

   - name: Enable and start osbuild-composer.socket
     ansible.builtin.service:
       name: osbuild-composer.socket
       enabled: yes
       state: started
     become: true