---

- name: deploy application to k8s
  hosts:
    - all
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: /tmp/kubeconfig
      validate_certs: false
  pre_tasks:
    - name: slurp up kubeconfig
      ansible.builtin.slurp:
        path: /var/lib/microshift/resources/kubeadmin/kubeconfig
      register: kubeconfig_raw
      become: true
    - name: create kubeconfig
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ (kubeconfig_raw['content'] | b64decode).replace('localhost', ansible_host) }}"
        dest: /tmp/kubeconfig
    - name: allow API access
      ansible.posix.firewalld:
        port: 6443/tcp
        zone: public
        state: enabled
        immediate: true
        permanent: true
      become: true
  tasks:
    - name: make calls from localhost
      delegate_to: localhost
      block:
        - name: create namespace
          kubernetes.core.k8s:
            name: dgw
            kind: Namespace
            state: present
        - name: patched namespace
          kubernetes.core.k8s:
            name: dgw
            kind: Namespace
            state: patched
            definition:
              metadata:
                labels:
                  pod-security.kubernetes.io/enforce: privileged
                  pod-security.kubernetes.io/audit: privileged
                  pod-security.kubernetes.io/warn: privileged
        - name: apply definitions
          kubernetes.core.k8s:
            namespace: dgw
            definition: "{{ lookup('file', yaml_file) | from_yaml }}"
          loop:
            - files/manifests/dgw/configmap.yaml
            - files/manifests/dgw/secret.yaml
            - files/manifests/dgw/mqtt-setting.yaml
            - files/manifests/dgw/pvc-sdcard.yaml
            - files/manifests/dgw/pvc-dxpgateway.yaml
            - files/manifests/dgw/sa.yaml
            - files/manifests/dgw/clusterrole.yaml
            - files/manifests/dgw/rolebinding.yaml
            - files/manifests/dgw/service.yaml
            - files/manifests/dgw/route.yaml
            - files/manifests/dgw/deployment.yaml
          loop_control:
            loop_var: yaml_file