---
- name: Deploy application on microshift
  hosts: all
  tasks:
    - name: MicroShiftサービスの状態をStartedであることを確認する
      ansible.builtin.systemd:
        name: microshift.service
      register: microshift_status
      become: yes
    - debug:
        var: microshift_status.status.ActiveState