---
- name: Deploy application on microshift
  hosts: all
  tasks:
    - name: Deploy application
      vars:
        microshift_image_pull_secret: "{{ lookup('file', '~/pull-secret.txt') }}"
        microshift_app_manifests:
          - ./offline-manifests/kustomization
          - ./offline-manifests/namespace
          - ./offline-manifests/argocd-crd
          - ./offline-manifests/argocd-clusterrolebinding
          - ./offline-manifests/argocd-rolebinding
          - ./offline-manifests/argocd-cluster
          - ./offline-manifests/argocd-application
          - ./offline-manifests/argocd-apps
      ansible.builtin.import_role:
        name: edge.microshift.app

    - name: Restart service microshift service
      service:
        name: microshift
        state: restarted