---
- name: Deploy application on microshift
  hosts: all
  tasks:
    - name: Deploy application
      vars:
        microshift_image_pull_secret: "{{ lookup('file', '~/pull-secret.txt') }}"
        microshift_app_manifests:
          - /microshift/argocd/kustomization.yaml
          - /microshift/argocd/namespace.yaml
          - /microshift/argocd/argocd-crd.yaml
          - /microshift/argocd/argocd-clusterrolebinding.yaml
          - /microshift/argocd/argocd-rolebinding.yaml
          - /microshift/argocd/argocd-cluster.yaml
          - /microshift/argocd/argocd-application.yaml
          - /microshift/argocd/argocd-apps.yaml
      ansible.builtin.import_role:
        name: edge.microshift.app
