---
- name: MicroShiftサービスの正常性確認手順
  hosts: all
  ignore_unreachable: yes
  tasks:
    - name: MicroShiftサービスの状態を起動状態にする
      ansible.builtin.systemd:
        name: microshift.service
        state: started
      become: yes