---
- name: Deploy application on microshift
  hosts: all
  tasks:
    - name: MicroShiftサービスの状態を起動状態にする
      ansible.builtin.systemd:
        name: microshift.service
        state: started
      become: yes