---
- name: Run Microshift rpm install role
  hosts: all
  gather_facts: true
  tasks:
    - name: Install Microshift on rpm based system
      ansible.builtin.import_role:
        name: edge.microshift.rpm_install