---
- name: PLCコンテナの存在確認
  hosts:
    - all
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: /tmp/kubeconfig
      validate_certs: false
    kubernetes.core.k8s_info:
      kubeconfig: /tmp/kubeconfig
      validate_certs: false
      wait: true
      wait_condition:
        type: Ready
        status: "True"
  pre_tasks:
    - name: slurp up kubeconfig
      ansible.builtin.slurp:
        path: /var/lib/microshift/resources/kubeadmin/kubeconfig
      register: kubeconfig_raw
      become: true
    - name: create kubeconfig
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ (kubeconfig_raw['content'] | b64decode).replace('localhost', ansible_host) }}"
        dest: /tmp/kubeconfig
    - name: allow API access
      ansible.posix.firewalld:
        port: 6443/tcp
        zone: public
        state: enabled
        immediate: true
        permanent: true
      become: true
  tasks:
    - name: make calls from localhost
      delegate_to: localhost
      block:
        - name: get pods in plc
          kubernetes.core.k8s_info:
            kind: Pod
            namespace: plc
          retries: 5
          delay: 10
        - name: get pods in openshift-ovn-kubernetes
          kubernetes.core.k8s_info:
            kind: Pod
            namespace: openshift-ovn-kubernetes
          retries: 5
          delay: 10
        - name: get pods in openshift-dns
          kubernetes.core.k8s_info:
            kind: Pod
            namespace: openshift-dns
          retries: 5
          delay: 10
        - name: get pods in openshift-service-ca
          kubernetes.core.k8s_info:
            kind: Pod
            namespace: openshift-service-ca
          retries: 5
          delay: 10
        - name: get pods in openshift-storage
          kubernetes.core.k8s_info:
            kind: Pod
            namespace: openshift-storage
          retries: 5
          delay: 10
        - name: get pods in openshift-ingress
          kubernetes.core.k8s_info:
            kind: Pod
            namespace: openshift-ingress
          retries: 5
          delay: 10