---
 - hosts: all
   tasks:
   - name: カスタマーポータルへの登録
     community.general.redhat_subscription:
       username: "{{ redhat_username }}"
       password: "{{ redhat_password }}"
       pool_ids: "{{ pool_id }}"
     become: true

   - name: subscription-managerの利用可能なリポジトリの確認
     ansible.builtin.shell:
       cmd: subscription-manager config | grep -i 'manage_repos = [0]'
     register: subman_repo_control
     changed_when: false
     check_mode: false
     failed_when: false
     become: true

   - name: リポジトリの有効化
     ansible.builtin.shell:
       cmd: subscription-manager config --rhsm.manage_repos=1
     when:
       - subman_repo_control.rc | int == 0
     become: true

   - name: remove the rhui repo file
     ansible.builtin.file:
       path: /etc/yum.repos.d/redhat-rhui.repo
       state: absent
     become: true

   - name: remove the other rhui repo file
     ansible.builtin.file:
       path: /etc/yum.repos.d/redhat-rhui-client-config.repo
       state: absent
     become: true

   - name: remove rhui cron job
     ansible.builtin.file:
       path: /etc/cron.daily/update-client-config-packages
       state: absent
     become: true

   - name: enable baseos/appstream
     community.general.rhsm_repository:
       name: "{{ common_repos }}"
       state: enabled
     become: true

   - name: enable fast-dp/ocp
     community.general.rhsm_repository:
       name: "{{ extra_repos }}"
       state: enabled
     become: true
