---
- hosts: all
  gather_facts: no
  tasks:
    - name: Create inventory dictionary
      set_fact:
        inventory_dict: "{{ hostvars | dict2items | map(attribute='value') | map(attribute='ansible_host') | zip(ansible_play_hosts_all) | list }}"

    - name: set var
      set_fact:
        inventory_dict: "{{ dict(inventory_dict) }}"

    - debug: var=inventory_dict

    - name: Create inverted inventory dictionary
      set_fact:
        inverted_inventory_dict: "{{ inventory_dict | dict2items | map(attribute='value') | zip(inventory_dict | dict2items | map(attribute='key')) | list }}"

    - name: Create inverted inventory dictionary
      set_fact:
        inverted_inventory_dict: "{{dict(inverted_inventory_dict)}}"

    - name: Display inventory dictionary
      debug:
        var: inverted_inventory_dict
    - name: test
      set_fact:
        test: "{{ inverted_inventory_dict[0] }}"

    - debug: var=test