---
- name: エッジデバイス上の仮想マシンを操作する
  hosts:
    - all
  become: yes
  gather_facts: yes
  vars: # デフォルト変数
    vmname: simulation # namespace
    operate: reboot #アプリケーション名(マニフェストのディレクトリ名と同じにすること)
  ignore_unreachable: yes

  tasks:
    - name: "VMのステータスを確認"
      command: virsh list --all
      register: vm_status
    - name: "結果を出力"
      debug:
        msg: "{{ vm_status }}"

    - name: "{{ vmname }} VMへ操作"
      command: virsh {{ operate }} {{ vmname }}
      register: result

    - name: "結果を出力"
      debug:
        msg: |
            "{{ result }}"