---

- name: import pre-flight tasks
  ansible.builtin.import_tasks: pre-flight.yml

- name: import install tasks
  ansible.builtin.import_tasks: install.yml

- name: import configure
  ansible.builtin.import_tasks: configure.yml
