---

# Lazy workaround, what I really should do is strip the DNS servers off the external interface and just use the dnsmasq container once up
- name: put entries into /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: EOF
    line: "{{ dns_entry.address }} {{ dns_entry.record.split('.')[0] }} {{ dns_entry.record }}"
  loop: "{{ service.templates.1.vars.dns_entries }}"
  loop_control:
    loop_var: dns_entry
  become: true
