---

- name: copy cert to correct location
  ansible.builtin.copy:
    src: ~/workshop-certs/{{ ec2_name_prefix }}.{{ workshop_dns_zone }}/{{ ec2_name_prefix }}-fullchain.crt
    dest: "{{ build_dir }}/reverse-proxy/server.crt"
    remote_src: true

- name: copy key to correct location
  ansible.builtin.copy:
    src: ~/workshop-certs/{{ ec2_name_prefix }}.{{ workshop_dns_zone }}/{{ ec2_name_prefix }}.pem
    dest: "{{ build_dir }}/reverse-proxy/server.key"
    remote_src: true
