---

- name: push blueprint template
  ansible.builtin.template:
    src: templates/blueprint.toml.j2
    dest: "/home/students/{{ device.manufacturer }}-blueprint.toml"
    owner: "{{ ansible_user }}"

- name: push blueprint into image builder
  infra.osbuild.push_blueprint:
    src: "/home/students/{{ device.manufacturer }}-blueprint.toml"
  vars:
    fdo:
      manufacturing_server_url: "{{ manufacturing_server_url }}"
      manufacturing_server_port: "{{ manufacturing_server_port }}"
