apiVersion: v1
kind: ConfigMap
metadata:
  name: quality-handler-config
  namespace: cps
data:
  MODEL_GEN_ADDRESS: "http://model-gen-cps.apps.192.168.3.100.nip.io"
  SUB_TOPIC: "result"
  MQTT_BROKER_ADDRESS: "amq-broker-hdls-svc"
  MQTT_PORT: "61616"
  KAFKA_USE: "" # NULL -> MQTT mode, True -> Kafka mode
  KAFKA_BOOTSTRAP_SERVER: "my-cluster-kafka.demo:9092"
  PER_CYCLES: "3"
  MODEL_CREATE_THRESHOLD: "1"
  MODEL_GEN_TIMEOUT: "3.0"