apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: quality-handler
  labels:
    app: quality-handler
  name: quality-handler
  namespace: cps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quality-handler
  strategy: {}
  template:
    metadata:
      annotations:
        app: quality-handler
      labels:
        app: quality-handler
    spec:
      containers:
      - image: registry.gitlab.com/yono1/cps-demo/quality-handler:v1.0
        imagePullPolicy: IfNotPresent
        name: quality-handler
        envFrom:
          - configMapRef:
              name: quality-handler-config
      restartPolicy: Always