---

- name: run additional roles if needed
  hosts:
    - edge_management
    - edge_remote_management
  become: true
  vars_files:
    - "workshop_vars/{{ workshop_type }}.yml"
  pre_tasks:
    - name: assign extra roles for rhde_fdo_rtk
      ansible.builtin.set_fact:
        extra_roles:
          - ../roles/setup_fdo
          - ../roles/edge_simplified_installers
      when:
        - workshop_type == 'rhde_fdo_rtk'
    - name: assign extra roles for summit connect 2023 demo
      ansible.builtin.set_fact:
        extra_roles:
          - ../roles/set_active_image
        desired_image_version: 1.0.0
      when:
        - demo_type is defined and demo_type == 'summit_connect_2023'
  tasks:
    - name: run extra roles
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop: "{{ extra_roles }}"
      loop_control:
        loop_var: role
      when:
        - extra_roles is defined
