---

- name: Create lab instances in AWS
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  # vars_files:
  #   - "{{ _vars_file_path }}"
  tasks:
    - include_role:
        name: ../roles/manage_ec2_instances
      when:
        - run_in_aws is defined
        - run_in_aws | bool
