---

- name: setup gitea
  hosts:
    - edge_management
    - edge_remote_management
  pre_tasks:
    - name: Include workshop or demo variables
      include_vars:
        file: "{{ playbook_dir }}/workshop_vars/{{ workshop_type }}.yml"
      when: workshop_type is defined
      ignore_errors: yes

    - name: Include demo variables
      include_vars:
        file: "{{ playbook_dir }}/demo_vars/{{ demo_type }}.yml"
      when: demo_type is defined
  tasks:
    - name: include gitea setup role
      ansible.builtin.include_role:
        name: ../roles/setup_gitea
