---

- name: Configure hypervisors
  hosts:
    - hypervisors
  tasks:
    - name: Include student user config role
      ansible.builtin.include_role:
        name: ../roles/student_users
        apply:
          become: true

    - name: Include hypervisor config role
      ansible.builtin.include_role:
        name: ../roles/edge_hypervisor
