---

- name: setup ansible controller
  hosts:
    - edge_management
    - edge_remote_management
  become: true
  tasks:
    - name: setup ansible controller
      ansible.builtin.include_role:
        name: ../roles/control_node