---

- name: borrow Dr. Evil's henchman
  hosts:
    - edge_management
  become: true
  vars_files:
    - "{{ playbook_dir }}/workshop_vars/{{ workshop_type }}.yml"
  tasks:
    - name: import random tasks role
      ansible.builtin.include_role:
        name: ../roles/random_task
