---

- name: setup rhsm
  hosts:
    - edge_management
    - controller
    - hypervisors
    - edge_local_management
    - edge_remote_management
  become: true
  tasks:
    - name: register to rhsm
      ansible.builtin.include_role:
        name: ../roles/rhsm
