---

- name: create student users on edge managers
  hosts:
    - edge_management
    - edge_remote_management
  become: true
  pre_tasks:
    - name: Include workshop or demo variables
      include_vars:
        file: "{{ playbook_dir }}/workshop_vars/{{ workshop_type }}.yml"
      when: workshop_type is defined
      ignore_errors: yes

    - name: Include demo variables
      include_vars:
        file: "{{ playbook_dir }}/demo_vars/{{ demo_type }}.yml"
      when: demo_type is defined
  tasks:
    - name: Include student_users role when appropriate
      ansible.builtin.include_role:
        name: ../roles/student_users
      when:
        - workshop_or_demo is not defined or
          workshop_or_demo == 'workshop'

