---

# If your local device running as the edge manager node is slower,
# use this to sync from a faster device, such as a bare metal instance in aws

# set var in extra-vars:
# sync_from: 'edge_manager_aws'

# This automatically syncs to all hosts in the 'backup' group

- name: set vars so this doesn't fail
  hosts: localhost
  gather_facts: false
  tasks:
    - name: define sync_from hosts
      ansible.builtin.add_host:
        name: "{{ sync_from }}"
        groups:
          - group_sync_from
      when:
        - sync_from is defined

- name: pull content from source
  hosts:
    - group_sync_from
  pre_tasks:
    - name: create landing dir
      ansible.builtin.file:
        path: /tmp/images_sync
        state: directory
      delegate_to: localhost
  tasks:
    - name: pull contents of /var/www/html/
      ansible.posix.synchronize:
        src: /var/www/html/
        dest: /tmp/images_sync/
        mode: pull
        recursive: true
        checksum: true
        rsync_opts:
          - "--exclude=*.lock"

- name: push content to backups
  hosts:
    - backups
  pre_tasks:
    - name: create a landing dir
      ansible.builtin.file:
        path: /tmp/synced_images
        state: directory
  tasks:
    - name: push files
      ansible.posix.synchronize:
        src: /tmp/images_sync/
        dest: /tmp/synced_images
        mode: push
        recursive: true
        checksum: true
      notify:
        - move_to_webdir
        - restore_permissions
        - restore_context
  handlers:
    - name: copy files to /var/www/html
      ansible.builtin.copy:
        src: /tmp/synced_images/
        dest: /var/www/html/
        remote_src: true
      become: true
      listen:
        - move_to_webdir
    - name: restore permissions
      ansible.builtin.shell:
        cmd: chown -R apache:apache /var/www/html
      become: true
      listen:
        - restore_permissions
    - name: restore context
      ansible.builtin.shell:
        cmd: restorecon -R /var/www/html
      become: true
      listen:
        - restore_context

- name: cleanup localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: dump tmp dir
      ansible.builtin.file:
        path: /tmp/synced_images
        state: absent
