---

- name: issue wildcard cert
  hosts:
    - edge_remote_management
    - edge_local_management
    - edge_management
    - hypervisors
  serial: 1
  pre_tasks:
    - name: become for these tasks
      become: true
      block:
        - name: ensure pip is available
          ansible.builtin.dnf:
            name: python3-pip
        - name: install python libraries
          ansible.builtin.pip:
            name:
              - cryptography
              - botocore
              - boto3
  tasks:
    - name: get wildcard cert if possible
      when:
        - dns_type == 'aws'
      block:
        - name: make a directory for cert storage
          ansible.builtin.file:
            path: "{{ directory }}"
            state: directory
          loop:
            - "~/workshop-certs"
            - "~/workshop-certs/{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
          loop_control:
            loop_var: directory
        - name: issue base domain cert
          ansible.builtin.include_role:
            name: ../roles/zerossl_cert
          vars:
            domain_name: "{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
            _cert_dir: "~/workshop-certs/{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
            _cert_owner: "{{ ansible_user }}"
            _cert_group: "{{ ansible_user }}"
            wildcard: true
