apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: led-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: led-clusterrole
subjects:
- kind: ServiceAccount
  name: led