---

- name: Import preflight tasks
  ansible.builtin.import_tasks: pre-flight.yml

- name: Import cert-manager operator install tasks
  ansible.builtin.import_tasks: cert-manager-operator.yml

- name: Import ingress config tasks
  ansible.builtin.import_tasks: update-ingress-cert.yml

- name: Import api config tasks
  ansible.builtin.import_tasks: update-api-cert.yml
