---

- name: Request API certificates
  redhat.openshift.k8s:
    template: templates/api-certificates.yaml.j2
  notify:
    - wait_for_certs

- name: Update api
  redhat.openshift.k8s:
    template: templates/apiserver.yaml.j2
  notify:
    - wait_for_certs
    - update_kubeconfig
