apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dgw
spec:
  host: dgw.192.168.3.101.nip.io
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: dgw
    weight: 100
  wildcardPolicy: None